# sleep 1000
# mysql -h db -u root -p$MARIADB_ROOT_PASSWORD -e "CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD'; GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD'"
mysql -h db -u root -p$MARIADB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';"
mysql -h db -u $MARIADB_USER -p$MARIADB_PASSWORD -e "CREATE DATABASE $MARIADB_NAME;"

sls offline start -o 0.0.0.0